### ISSUE TITLE
content string not rendered properly

### ISSUE THREAD

**Issue by simon-schuster44** [sjdemartini/mui-tiptap#177]
### Describe the bug

Ok, maybe that's also a bug that happens because of my shadow dom. But when I give an initial value to the content property, the html and the styling is not right.

### To Reproduce

when I give the string 
`"<p><span style="color: #333333; font-family: helvetica, 'microsoft sans serif', arial, sans-serif; font-size: 12px; background-color: #ffffdd;">Der Untersuchungsrahmen nach &sect;7 NABEG weist auf die M&ouml;glichkeit von</span></p>"`

to the content, the html rendered this: 
`<p><span style="color: #333333">Der Untersuchungsrahmen nach §7 NABEG weist auf die Möglichkeit von</span></p>
`
so half of the styling is missing...

### System (please complete the following information):

- mui-tiptap version: 1.8.5
- tiptap version: 2.1.12
- Browser: chrome
- OS: win11

### Additional context

BTW great work you're doing, the best looking and working editor I've seen so far...

**Comment by sjdemartini** [comment]
@simon-schuster44 I'm not very familiar with utilizing React components (or mui-tiptap) with the shadow dom. Would you be able to provide a CodeSandbox (I recommend forking the one linked from the README) so I can see the full code used in the above example and take a look? 

Side note in case it's the cause of your issue: if you do not include all of the relevant extensions in your editor's `extensions` array, Tiptap will remove unrecognized markup. For instance, in your example, you need to ensure that `Color`, `FontFamily`, `Highlight`, and `TextStyle` (used by color and font-family) are all included in the `extensions` array.

If this turns out to be a more general problem with Tiptap itself and not specific to mui-tiptap, I'd recommend filing an issue here https://github.com/ueberdosis/tiptap.

**Comment by simon-schuster44** [comment]
Hey, thanks for the quick response. I've created a Sandbox with a part of my current Project. Unfortunately (for me, not for you ) the Sandbox seems to run just fine, so I'll close this issue and search in my code for errors. I'll come back if I should run into an error again. And again, great work you're doing!

https://codesandbox.io/s/heuristic-lumiere-9qv4zl?file=/src/Editor.tsx:1029-1039

**Comment by simon-schuster44** [comment]
Maybe one last addition, because I'm really struggling right now... It seems as if the Color picker opens onClick and immediately closes again. have you ever had that issue or maybe know what could cause it?

**Comment by sjdemartini** [comment]
Okay, I appreciate you following up! And thanks for the kind words and for using mui-tiptap!
