### ISSUE TITLE
onUpdate callback from useEditor hook not called when setting content to editor programmatically

### ISSUE THREAD

**Issue by woigl** [sjdemartini/mui-tiptap#199]
### Describe the bug

I am using the following code programmatically to set a new content to my editor:
`const currentSelection = editor?.state.selection || 0;
editor?.chain().setContent(newContent).setTextSelection(currentSelection).run();`

I was expecting that the useEditor hook callback for onUpdate would be called. Is there any callback that gets executed when setting the content for the editor programmatically?

### Expected behavior

Setting the content programmatically to the editor should call the useEditor hook onUpdate callback.

**Comment by sjdemartini** [comment]
@woigl The question you're asking is all for Tiptap itself, and not pertaining to mui-tiptap. Please use Stack Overflow or perhaps the Tiptap repo (https://github.com/ueberdosis/tiptap) for this sort of thing in the future, after looking through Tiptap's docs, rather than posting here. For this particular issue, I happen to know you can use `setContent(content, true)`, since the second argument is an `emitUpdate` boolean which defaults to `false`: https://tiptap.dev/docs/editor/api/commands/set-content (or see code [here](https://github.com/ueberdosis/tiptap/blob/e97630c63927b3c05e75882975ea12c4d364acd3/packages/core/src/commands/setContent.ts#L21-L30)). I'll close this out.

**Comment by woigl** [comment]
@sjdemartini, I'm sorry. I thought the onUpdate was part of the mui-tiptap. Thanks a lot for the hint, which works perfectly!
