### ISSUE TITLE
Question: How to skip showing the anchor for Headings in readonly mode?

### ISSUE THREAD

**Issue by vitality82** [sjdemartini/mui-tiptap#210]
Question:

I know this is a weird question, since HeadingWithAnchor has an opinion in the name itself, but is there perhaps a standard way to avoid showing those anchor links on hover?

The solutions I can think of:

1. Implement my own custom component based on TipTaps heading
2. A custom style override, e.g

```
.MuiTiptap-RichTextContent-readonly {
  .MuiTiptap-HeadingWithAnchorComponent-link {
    display: none;
  }
}
```

Motivation behind this is long form documents and non-unique headings.

**Comment by sjdemartini** [comment]
@vitality82 I assume you want the heading element IDs and anchor linking to be possible, but just not to show the anchor links on hover? If so, style overrides seem like a reasonable way to go. If you don't need heading links at all, then you should just use `Heading` from Tiptap (https://tiptap.dev/docs/editor/api/nodes/heading) instead of `HeadingWithAnchor`. `HeadingWithAnchor` exists specifically for adding anchors, but otherwise is identical to Tiptap's `Heading`.

**Comment by vitality82** [comment]
You're spot on. Thanks @sjdemartini and awesome work you've done! I'd be happy to help contributing (and learn some new things along the way) but I'm spread thin with work & family (at least for now).

**Comment by vitality82** [comment]
For anyone questioning later how to opt for the classic TipTap Heading (without anchors), you can just use it directly with MUI-Tiptap's MenuSelectHeading component.

In your useExtensions.js

```
import { Heading } from '@tiptap/extension-heading';

[
  ....
  ....
 // HeadingWithAnchor,  Replaced with:
Heading.configure({
   levels: [1, 2, 3],
   HTMLAttributes: {
      class: 'heading',
   },
}),
```
