### ISSUE TITLE
Rendering Content without `RichTextReadOnly`

### ISSUE THREAD

**Issue by Jasermon** [sjdemartini/mui-tiptap#245]
### Describe the bug

I created my editor using [CodeSandbox Repo](https://codesandbox.io/p/sandbox/mui-tiptap-demo-3zl2l6) as a reference. Everything works very well. My problem occurs when rendering the HTML code I receive with `getHTML()`.

If I had to give an example, here is the post in editor;

![image](https://github.com/user-attachments/assets/0d107b05-9418-41bd-b742-cc28002f83c0)

When I render it with the following code it looks like this:

`<Box dangerouslySetInnerHTML={{ __html: details.items.content }}`

![image](https://github.com/user-attachments/assets/9759f6ec-5636-46d1-abd0-7bf0199031ca)

When I render it with `RichTextReadOnly` it looks like this:

![image](https://github.com/user-attachments/assets/5abf5122-2144-40be-b05e-03e615eeb2ce)

But I don't want to use `RichTextReadOnly`. I have several reasons for this:

- With DevTools, when `contenteditable="false"` is set to `true`, the content becomes editable. ![image](https://github.com/user-attachments/assets/8452807f-e5be-4b68-9bcb-3ac85f6ee4cc)
- When you click on the images, a border is created around them.  ![image](https://github.com/user-attachments/assets/b4eb1da8-f04e-4faf-a0ae-2c50d49f4d64)

### Expected behavior

A component that allows the content received with `getHTML()` or `getJSON()` to be rendered as in the editor can solve this problem.

### System (please complete the following information)

- mui-tiptap version: 1.9.2
- tiptap version: 2.4.0
- Browser: Chrome
- Node version: v21.1.0
- OS: Windows
- Copy-paste your `extensions` array used for the editor

```jsx
export default function useExtensions({ placeholder } = {}) {
	return useMemo(() => {
		return [
			TableImproved.configure({
				resizable: true,
			}),
			TableRow,
			TableHeader,
			TableCell,
			BulletList,
			CodeBlock,
			Document,
			HardBreak,
			ListItem,
			OrderedList,
			Paragraph,
			CustomSubscript,
			CustomSuperscript,
			Text,
			Bold,
			Blockquote,
			Code,
			Italic,
			Underline,
			Strike,
			CustomLinkExtension.configure({
				autolink: true,
				linkOnPaste: true,
				openOnClick: false,
			}),
			LinkBubbleMenuHandler,
			Gapcursor,
			// HeadingWithAnchor,
			Heading,
			TextAlign.configure({
				types: ["heading", "paragraph", "image"],
			}),
			TextStyle,
			Color,
			FontFamily,
			FontSize,
			Highlight.configure({ multicolor: true }),
			HorizontalRule,
			ResizableImage,
			Dropcursor,
			TaskList,
			TaskItem.configure({
				nested: true,
			}),
			Placeholder.configure({
				placeholder,
			}),
			History,
		];
	}, [placeholder]);
}
```

**Comment by sjdemartini** [comment]
Hi @Jasermon, as mentioned in https://github.com/sjdemartini/mui-tiptap/issues/136#issuecomment-2049890241, `getHTML` is a serialized _representation_ of your content. While it can be used for display, there are Tiptap extensions where the Tiptap-based rendering of that content will visually differ from the serialized data due to JS-based logic used in rendering (where the serialized content is parsed but the visual representation is more involved).

For your particular extensions, which in general perhaps don't need any additional JS-based logic, you may be able to apply the mui-tiptap styles to your `dangerouslySetInnerHTML` element via using the `getEditorStyles` utility from mui-tiptap (e.g. similar to what the mui-tipap RichTextContent component does [here](https://github.com/sjdemartini/mui-tiptap/blob/872b5f23dd4d4c282c9213973d2c7f6287e8f0a5/src/RichTextContent.tsx#L25-L34)). 

In general though, if you want your editor and your serialized content to render/look the same, you should let Tiptap do the rendering, which is what `RichTextReadOnly` is for.

**Comment by Jasermon** [comment]
> Hi @Jasermon, as mentioned in [#136 (comment)](https://github.com/sjdemartini/mui-tiptap/issues/136#issuecomment-2049890241), `getHTML` is a serialized _representation_ of your content. While it can be used for display, there are Tiptap extensions where the Tiptap-based rendering of that content will visually differ from the serialized data due to JS-based logic used in rendering (where the serialized content is parsed but the visual representation is more involved).
> 
> For your particular extensions, which in general perhaps don't need any additional JS-based logic, you may be able to apply the mui-tiptap styles to your `dangerouslySetInnerHTML` element via using the `getEditorStyles` utility from mui-tiptap (e.g. similar to what the mui-tipap RichTextContent component does [here](https://github.com/sjdemartini/mui-tiptap/blob/872b5f23dd4d4c282c9213973d2c7f6287e8f0a5/src/RichTextContent.tsx#L25-L34)).
> 
> In general though, if you want your editor and your serialized content to render/look the same, you should let Tiptap do the rendering, which is what `RichTextReadOnly` is for.

Thanks for your answer. I have no problem using `RichTextReadOnly`, but I am bothered by the issue of setting the `contenteditable` prop to `true` with DevTools.

**Comment by sjdemartini** [comment]
@Jasermon Your concern is a user changing `contenteditable` to `true` via dev tools, and thereby being able to edit stuff they otherwise shouldn't be able to edit? I don't believe there's a way to prevent someone from manipulating the DOM manually/externally to the application. Even if this were preventable via JS, couldn't they also then manipulate the JS? I don't know that there will be reasonable ways to prevent it, but you could try looking through Tiptap's issues and discussions (https://github.com/ueberdosis/tiptap) and/or Prosemirror's to see if anyone else discussed something similar. This sort of thing is outside of mui-tiptap in particular. Good luck!
