### ISSUE TITLE
ESM compatibility - unable to build

### ISSUE THREAD

**Issue by tehbelinda** [sjdemartini/mui-tiptap#256]
### Describe the bug

When including extensions from mui tiptap in a node js environment with es modules, it fails to build

The error is:
 
```js
import { FontSize, } from "mui-tiptap";
         ^^^^^^^^
SyntaxError: Named export 'FontSize' not found. The requested module 'mui-tiptap' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'mui-tiptap';
const { FontSize, } = pkg;
``` 

Tried the default as suggested, but then that resulted in:

```js
(node:5017) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/project/workspace/node_modules/mui-tiptap/dist/esm/index.js:1
export { default as ControlledBubbleMenu, } from "./ControlledBubbleMenu";
^^^^^^

SyntaxError: Unexpected token 'export'
```

### To Reproduce

https://codesandbox.io/p/devbox/pensive-volhard-hyhtls

1. Run `npm start` to see the first error
2. Comment out the Case 1 imports and uncomment the Case 2 import
3. Run `npm start` again, see the second error

### Expected behavior

Running `npm start` should successfully build and run the index.ts code.

### Screenshots

N/A

### System (please complete the following information)

- mui-tiptap version: 1.9.5
- Node version: v20.9.0

### Additional context

I'm trying to convert HTML into a Tiptap format on a Hocuspocus nodejs server with TiptapTransformer (https://tiptap.dev/docs/guides/output-json-html), and would like to use the same Mui TipTap extensions that we use on our frontend for compatibility. I can import the rest of the Tiptap extensions without issues.

I noticed this package.json does have separate exports for import/require, so it seems like ESM should work. However it doesn't have `"type": "module",` could that be an issue?

**Comment by sjdemartini** [comment]
Thanks for reporting! I've opened a PR https://github.com/sjdemartini/mui-tiptap/pull/257 which I think should resolve it, based on some reading I did, but I haven't yet tested that it resolve the issue in a node project. Once I do, I'll plan to merge and publish a new version.

**Comment by sjdemartini** [comment]
@tehbelinda I've spent an inordinate amount of time trying to resolve this, and it's shockingly difficult to find a working solution. CJS vs ESM packaging/resolution is a frustrating mess! My original solution #257 didn't seem to work in practice, and #258 seemed to work in consuming bundled packages but then I tested on your node project where it still failed (even after trying to update imports for icons-material and lodash) 😢. So #259 seemed to be an approach that should hopefully work for various end-users, forcing CJS in the node environment.

I wouldn't be surprised if mui-tiptap still does not (and has never) properly packaged for ESM despite exporting files for that context, due to the quirks/incompatibilities with ESM in `mui/icons-material` and `lodash`, mentioned a bit in #259 (and attempted to resolve in #258). But I hadn't heard about specific problems to date, and from what I can tell this new approach of forcing CJS works 🤷 

Published in https://github.com/sjdemartini/mui-tiptap/releases/tag/v1.9.6. If you happen to have a better suggested fix or if this is still causing problems, I'd greatly appreciate suggestions on how it can be handled!

**Comment by sjdemartini** [comment]
@tehbelinda Glad it's working! Yeah, that's expected, since `@mui/material` [requires `@emotion/styled` as a peer dependency](https://github.com/mui/material-ui/blob/f43f3d5e50bed812c451905d6aa29203c4a8d500/packages/mui-material/package.json#L79): https://mui.com/material-ui/getting-started/installation/#default-installation   (this dep is listed in mui-tiptap's example install instructions, but it's not a peer of mui-tiptap, but rather a peer of a peer)

As for that Stack Overflow post, I did actually see that very post and did try rollup (via Vite library mode as mentioned in https://github.com/sjdemartini/mui-tiptap/pull/258#issue-2475139173). I didn't go too far with it, since it seemed less capable than `tsup`, which is what that PR was using. But I believe it will yield a similar result where `@mui/icons-material` and `lodash` do not work properly in ESM context, as mentioned in https://github.com/sjdemartini/mui-tiptap/pull/259. 😕
