### ISSUE TITLE
Update tiptap dependency

### ISSUE THREAD

**Issue by abianche** [sjdemartini/mui-tiptap#299]
### Is your feature request related to a problem? Please describe.

The tiptap dependency is far behind the latest version of tiptap. Would be great to get it updated to the latest version, to fix various bugs including a flushSync issue (https://github.com/ueberdosis/tiptap/issues/3580) that I am currently facing in my app.

### Describe the solution you'd like

All tiptap dependencies updated to the latest versions.

### Describe alternatives you've considered

None.

### Additional context

None.

**Comment by abianche** [comment]
I just saw that it might be related to what's described in https://github.com/sjdemartini/mui-tiptap/pull/45.
Are there any concrete plans already to migrate to the new tiptap version?

**Comment by sjdemartini** [comment]
@abianche You can use whatever tiptap version you like when you install it alongside mui-tiptap, as long as it is at least `2.0.0-beta.210`, per the open-ended peer dependencies defined here https://github.com/sjdemartini/mui-tiptap/blob/53a25ff479bb994d23860cc2bbc059237a2f3094/package.json#L88-L93

Internally for developing mui-tiptap, it uses an older version in the `devDependencies` (which helps with trying to ensure compatibility with older versions as well), but you don't have to stick with that version and should not be affected by it, since it does not restrict what version of tiptap is installed by end users.
