### ISSUE TITLE
React v19 breaks 'ref' & keyboard support

### ISSUE THREAD

**Issue by CHE1RON** [sjdemartini/mui-tiptap#300]
When using React v19 (currently in RC status), the `ref` cannot be passed correctly (since React v19 passes `ref`s as props I assume), therefore calling functions (like `upHandler` etc) stops working.

**Comment by sjdemartini** [comment]
@CHE1RON I haven't tested mui-tiptap with React 19, thanks for the heads up. You specifically reference `upHandler` which is actually not part of the published mui-tiptap package, but is just used in the internal "demo". Do you know what (if anything) breaks for mui-tiptap itself? Would you be able to provide any additional details if so? Thanks.

**Comment by CHE1RON** [comment]
Hey there @sjdemartini! I've been looking into this, and the issue appears when removing [this `forwardRef`](https://github.com/sjdemartini/mui-tiptap/blob/fabb746997cdf4e5a90cf114823c8cb965911c06/src/demo/SuggestionList.tsx#L28) and turning the `ref` into a prop (which should be redundant with React v19).

But you're right, it's not directly related to your awesome library 😎 Thanks for answering on such short notice! 

Cheers
CHE1RON

**Comment by sjdemartini** [comment]
Okay, thanks @CHE1RON, good to know! I haven't tried using React 19 or read into it in a lot of detail, but I'd have hoped that React 19 would be backward compatible and wouldn't break existing `forwardRef` usage, so that's unfortunate if it doesn't work in both 18 and 19. Glad you were able to resolve it regardless!
