### ISSUE TITLE
Add new menu buttons

### ISSUE THREAD

**Issue by bryanjtc** [sjdemartini/mui-tiptap#52]
### Is your feature request related to a problem? Please describe.

To make this package a true replacement for react-mui-draft-wysiwyg there are a few menu buttons that you can add.

### Describe the solution you'd like

Implement the following suggestions:
- [x] Undo menu button with `@tiptap/extension-history` (https://github.com/sjdemartini/mui-tiptap/pull/65)
- [x] Redo menu button with `@tiptap/extension-history` (https://github.com/sjdemartini/mui-tiptap/pull/65)
- [x] Highlight color menu button with `@tiptap/extension-highlight` (https://github.com/sjdemartini/mui-tiptap/pull/135)
- [x] Text color menu button with `@tiptap/extension-text-style` `@tiptap/extension-color` (https://github.com/sjdemartini/mui-tiptap/pull/135)
- [x] Add h4, h5, h6 to `MenuHeadingSelect`
- [x] Font size menu button with `@tiptap/extension-text-style` (new `FontSize` extension and `MenuSelectFontSize` in https://github.com/sjdemartini/mui-tiptap/pull/94 and #95)
- [x] Font family menu button with `@tiptap/extension-text-style` `@tiptap/extension-font-family` (https://github.com/sjdemartini/mui-tiptap/pull/110)
- [x] Align left menu button with `@tiptap/extension-text-align` (https://github.com/sjdemartini/mui-tiptap/pull/69, https://github.com/sjdemartini/mui-tiptap/pull/70)
- [x] Alight right menu button with `@tiptap/extension-text-align` (https://github.com/sjdemartini/mui-tiptap/pull/69, https://github.com/sjdemartini/mui-tiptap/pull/70)
- [x] Align center menu button with `@tiptap/extension-text-align` (https://github.com/sjdemartini/mui-tiptap/pull/69, https://github.com/sjdemartini/mui-tiptap/pull/70)
- [x] Justify menu button with `@tiptap/extension-text-align` (https://github.com/sjdemartini/mui-tiptap/pull/69, https://github.com/sjdemartini/mui-tiptap/pull/70)
- [x] Insert image menu button with `@tiptap/extension-image`
   - Using URL (see #136)
   - Uploading image (see #136)
- [x] Horizontal rule with `@tiptap/extension-horizontal-rule` (https://github.com/sjdemartini/mui-tiptap/pull/66)
- [x] Underline with `@tiptap/extension-underline` (https://github.com/sjdemartini/mui-tiptap/pull/68)

**Comment by sjdemartini** [comment]
I am intending to add more explicit support and built-in buttons for all of these, so thank you for filing and detailing this in such an organized way @bryanjtc! 

A couple of those are in fact already supported:
- `MenuHeadingSelect` handles all heading levels (h1-h6)—see [here](https://github.com/sjdemartini/mui-tiptap/blob/2cfbbf452611f493419d9a19e03d43c90e1b1abf/src/controls/MenuHeadingSelect.tsx#L251-L309). The default demo for local development in `mui-tiptap` happens to only configure the heading extension for levels h1-h3 (see [here](https://github.com/sjdemartini/mui-tiptap/blob/d58e6bbc04716378e9bf82908532e8698928549d/src/hooks/useRecommendedExtensions.ts#L139-L144)) but I can change the demo as well so it's more clear. As long as you configure your heading extension for all levels, `MenuHeadingSelect` will do the trick. When I add documentation to the repo and more polish to the app, this will be clearer. (Side note: that `useRecommendedExtensions` hook will be going away soon anyway as a part of cleaning up peer deps, since I don't think it's the right approach and everyone should simply choose their own extensions.)
- There's a general-purpose "insert image" button via [`MenuButtonAddImage`](https://github.com/sjdemartini/mui-tiptap/blob/c9886539ed06396f21d80eabacfd34d19732e6a3/src/controls/MenuButtonAddImage.tsx). You provide your own `onClick` (where you could use your own interface to type in a URL, or you could trigger a file upload). It's not part of the demo within the app, but I can add that. And perhaps I can provide a more explicit variant for an "insert image using URL" version. I think file-upload itself is best left to the application using `mui-tiptap`, since needs will inevitably vary, so I hope the simple `onClick` will do the trick. I use `MenuButtonAddImage` in an external app, and I find it works cleanly to have all file-upload logic handled external to `mui-tiptap` via the click.

**Comment by bryanjtc** [comment]
Removing `useRecommendedExtensions ` is a good idea. The demo should use the setup of the `useRecommendedExtensions` hook and all the other possible extensions and controls.
Can I add my own custom control using the `MenuButton ` component?

**Comment by bryanjtc** [comment]
The tooltip label should be a prop in all menu buttons to customize the label content.

**Comment by sjdemartini** [comment]
@bryanjtc Yes, that's the intention for `MenuButton`—to be a reusable base component so anyone can add their own menu buttons fairly easily. And agreed, I intend to have all props be overridable for all `MenuButton`s!

**Comment by sjdemartini** [comment]
FYI you can now override `tooltipLabel`s (and any other props) for all of the `MenuButton*` components, in [v1.0.0-beta.3](https://github.com/sjdemartini/mui-tiptap/releases/tag/v1.0.0-beta.3)

**Comment by sjdemartini** [comment]
The latest release [v1.0.0-beta.5](https://github.com/sjdemartini/mui-tiptap/releases/tag/v1.0.0-beta.5) includes several more controls components (undo, redo, horizontal rule, underline, and multiple options for text-align)

**Comment by sjdemartini** [comment]
The latest release [v1.0.0-beta.10](https://github.com/sjdemartini/mui-tiptap/releases/tag/v1.0.0-beta.10) features a new `FontSize` extension and `MenuSelectFontSize` controls component (see https://github.com/sjdemartini/mui-tiptap/pull/94 and #95 for some screenshots and examples).

**Comment by bryanjtc** [comment]
**Ideas to improve the menu image button:**
Original react-mui-draft-wysiwyg image button:
![image](https://github.com/sjdemartini/mui-tiptap/assets/49354825/0a4e936c-1216-43d1-ab32-59ecc083cb2f)
Upload:
![image](https://github.com/sjdemartini/mui-tiptap/assets/49354825/bf57b712-1162-4d8c-985c-fb08776cd716)
Url:
![image](https://github.com/sjdemartini/mui-tiptap/assets/49354825/55a6d8ce-fcea-44a8-afff-fb577ee113fa)

**Original mui-rte image button:**
![image](https://github.com/sjdemartini/mui-tiptap/assets/49354825/8e5395d7-e1ca-458e-9d0d-20d10f13024f)
Allow modifying height and width:
![image](https://github.com/sjdemartini/mui-tiptap/assets/49354825/aae7e5ae-3250-4dfd-9687-abc0784bc69a)
Allow choosing between image or video
![image](https://github.com/sjdemartini/mui-tiptap/assets/49354825/00037806-d9bc-4157-bdb6-9ec94a75d294)

**Comment by bryanjtc** [comment]
### Font color/highlight customization ideas
**Original react-mui-draft-wysiwyg image button:**
![image](https://github.com/sjdemartini/mui-tiptap/assets/49354825/7afae378-503d-4bc3-80ea-5895a42591ee)
**Tiptap example**
![image](https://github.com/sjdemartini/mui-tiptap/assets/49354825/3c543693-60a9-42f2-9c3c-e75ddae831fa)

**Comment by sjdemartini** [comment]
`MenuSelectFontFamily` has been added as of the [v1.2.0](https://github.com/sjdemartini/mui-tiptap/releases/tag/v1.2.0) version just published:
<img width="900" alt="Screenshot 2023-07-23 at 4 21 15 PM" src="https://github.com/sjdemartini/mui-tiptap/assets/1647130/14d4868b-dc37-476c-bf22-e9baf3aaa201">

**Comment by devth** [comment]
This project is amazing! Love the high velocity and quality ya'll are shipping. Thanks so much for building it. 🙏🏻

**Comment by cgil** [comment]
Second on the impressive speed! And also the text and highlight color input components

**Comment by sjdemartini** [comment]
Just commenting to say I haven't forgotten about this and aim to tackle the text and highlight color menu components soon. I have a WIP version but have a bit more work to do to polish it.

**Comment by sjdemartini** [comment]
I've released mui-tiptap [v1.5.0](https://github.com/sjdemartini/mui-tiptap/releases/tag/v1.5.0) which includes the first version of the text-color and highlight-color menu controls (along with some building-block components you can use to build a more custom version). Thanks for all the comments and suggestions in this thread!

I'm going to close out this issue, since those were the last outstanding extensions here which were missing support in mui-tiptap. I've added a separate issue https://github.com/sjdemartini/mui-tiptap/issues/136 to track future improvement ideas for the "Insert image" menu button, based on the above discussion.

Let me know if you have any feedback, and as usual feel free to file an issue if you come across bugs or have feature-request ideas!
