### ISSUE TITLE
Incorrect position of MuiTiptap-ControlledBubbleMenu-root

### ISSUE THREAD

**Issue by bryanjtc** [sjdemartini/mui-tiptap#53]
### Describe the bug

When I selected the Link Menu Button it shows in the wrong place. I traced the problem to the transform that the class `MuiTiptap-ControlledBubbleMenu-root` has.

### To Reproduce

1. Select the Link Menu Button

### Expected behavior

The bubble menu should be centered or below the link menu button.

### Screenshots

![image](https://github.com/sjdemartini/mui-tiptap/assets/49354825/f9e747a4-3e33-4619-bd34-2ab08f2e17f0)

### System (please complete the following information):

 - mui-tiptap version: [e.g. 1.0.0-beta.1]
 - tiptap version: 2.0.3
 - Browser: Chrome
 - Node version: 18
 - OS: Windows 11

**Comment by sjdemartini** [comment]
Hm, I see what you mean and why this is confusing. The behavior is that the link bubble button appears over the user's cursor/caret text-selection within the editor (or as near as Popper.js can accommodate), which is the location at which the link will appear.

For instance, it will show up above (or below as a fallback if there's not room) and center-aligned when clicking on an existing link or clicking on the button menu when you've moved your cursor over an existing link:
<img width="263" alt="image" src="https://github.com/sjdemartini/mui-tiptap/assets/1647130/85847c1e-3271-4b53-ade5-ae1ef6c1527c">

Or if you've clicked the link menu button to add a new link that way (as opposed to highlighting text and clicking it), it will similarly be above (or below) and center-aligned with that location. In this case below my cursor was just after "after this ":
<img width="480" alt="image" src="https://github.com/sjdemartini/mui-tiptap/assets/1647130/47f6adb3-70f9-4e02-939b-2aa034ce8a48">

In your example screenshot above, however, the editor content height is very short (just a single line), and the user selection/cursor is at the very start of it, so you're seeing the bubble menu be center-aligned over that. (So the positioning seems a bit more "random".)

I suppose one option instead could be to anchor the bubble menu to the link menu button position, whenever opening via clicking the menu button, rather than anchoring to the user's caret location within the editor. What do you think?

**Comment by bryanjtc** [comment]
Yeah it's better anchoring the bubble menu to the link menu button position,

**Comment by sjdemartini** [comment]
The fix described above has been released in 1.0.0-beta.4!
